import 'product.dart';
import 'package:e_commerce/models/product.dart';

final List<Product> mockProducts = [
  Product(
    id: '1',
    title: 'iPhone 14 Pro',
    description: 'Latest Apple smartphone with advanced features.',
    imageUrl: 'https://picsum.photos/id/101/200/300',
    price: 999.99,
    category: ProductCategory.phones,
  ),
  Product(
    id: '2',
    title: 'Samsung Galaxy S22',
    description: 'Flagship Samsung phone with stunning display.',
    imageUrl: 'https://picsum.photos/id/102/200/300',
    price: 899.99,
    category: ProductCategory.phones,
  ),
  Product(
    id: '3',
    title: 'iPad Pro',
    description: 'Apple tablet with M1 chip.',
    imageUrl: 'https://picsum.photos/id/109/200/300',
    price: 799.99,
    category: ProductCategory.tablets,
  ),
  Product(
    id: '4',
    title: 'Samsung Galaxy Tab S8',
    description: 'High-end Android tablet.',
    imageUrl: 'https://picsum.photos/id/110/200/300',
    price: 699.99,
    category: ProductCategory.tablets,
  ),
  Product(
    id: '5',
    title: 'Sony WH-1000XM4',
    description: 'Industry-leading noise cancelling headphones.',
    imageUrl: 'https://picsum.photos/id/107/200/300',
    price: 299.99,
    category: ProductCategory.headphones,
  ),
  Product(
    id: '6',
    title: 'Bose QuietComfort 45',
    description: 'Comfortable and high-quality headphones.',
    imageUrl: 'https://picsum.photos/id/111/200/300',
    price: 329.99,
    category: ProductCategory.headphones,
  ),
  Product(
    id: '7',
    title: 'JBL Flip 6',
    description: 'Portable Bluetooth speaker.',
    imageUrl: 'https://picsum.photos/id/112/200/300',
    price: 119.99,
    category: ProductCategory.speakers,
  ),
  Product(
    id: '8',
    title: 'Ultimate Ears BOOM 3',
    description: 'Waterproof wireless speaker.',
    imageUrl: 'https://picsum.photos/id/113/200/300',
    price: 149.99,
    category: ProductCategory.speakers,
  ),
  Product(
    id: '9',
    title: 'Canon EOS R5',
    description: 'Professional mirrorless camera.',
    imageUrl: 'https://picsum.photos/id/114/200/300',
    price: 3899.99,
    category: ProductCategory.cameras,
  ),
  Product(
    id: '10',
    title: 'Nikon Z6 II',
    description: 'Versatile full-frame camera.',
    imageUrl: 'https://picsum.photos/id/115/200/300',
    price: 1999.99,
    category: ProductCategory.cameras,
  ),
  Product(
    id: '11',
    title: 'PlayStation 5',
    description: 'Next-gen gaming console.',
    imageUrl: 'https://picsum.photos/id/116/200/300',
    price: 499.99,
    category: ProductCategory.gaming,
  ),
  Product(
    id: '12',
    title: 'Xbox Series X',
    description: 'Powerful gaming console from Microsoft.',
    imageUrl: 'https://picsum.photos/id/117/200/300',
    price: 499.99,
    category: ProductCategory.gaming,
  ),
  Product(
    id: '13',
    title: 'Apple Watch Series 8',
    description: 'Smartwatch with health tracking.',
    imageUrl: 'https://picsum.photos/id/105/200/300',
    price: 399.99,
    category: ProductCategory.smartwatches,
  ),
  Product(
    id: '14',
    title: 'Samsung Galaxy Watch 5',
    description: 'Feature-rich smartwatch.',
    imageUrl: 'https://picsum.photos/id/106/200/300',
    price: 349.99,
    category: ProductCategory.smartwatches,
  ),
  Product(
    id: '15',
    title: 'Google Nest Hub',
    description: 'Smart display for your home.',
    imageUrl: 'https://picsum.photos/id/118/200/300',
    price: 99.99,
    category: ProductCategory.smarthome,
  ),
  Product(
    id: '16',
    title: 'Amazon Echo Dot',
    description: 'Smart speaker with Alexa.',
    imageUrl: 'https://picsum.photos/id/119/200/300',
    price: 49.99,
    category: ProductCategory.smarthome,
  ),
  Product(
    id: '17',
    title: 'Mystery Box',
    description: 'A surprise tech gadget!',
    imageUrl: 'https://picsum.photos/id/120/200/300',
    price: 59.99,
    category: ProductCategory.other,
  ),
]; 